# Site
name: "Cybernetica"
title: "Cybernetica"
description: "For all things Cybernetic and Mechatronic"
logo: 'assets/images/Connexions.png'
favicon: 'assets/images/Connexions.png'
baseurl: /
google_analytics: 'UA-130118775-2'
disqus: 'cybernetica'
mailchimp-list: 'https://gmail.us20.list-manage.com/subscribe/post?u=0909bfb66d8058d274e5c232b&amp;id=664d3828a9'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
   conor:
    name: Conor
    display_name: Conor
    avatar: ''
    email: orrbifold@gmail.com
    IG: https://instagram.com/twiximus
    description: "Science guy"
    

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
